import { jsPDF } from 'jspdf'

// ─── Color palette ──────────────────────────────────────────────────
const BLUE = '#2563eb'
const DARK = '#1e293b'
const GRAY = '#64748b'
const LIGHT_GRAY = '#f1f5f9'
const WHITE = '#ffffff'
const ACCENT_GREEN = '#16a34a'
const ACCENT_AMBER = '#d97706'

// ─── Layout constants ───────────────────────────────────────────────
const PAGE_W = 210 // A4 mm
const PAGE_H = 297
const MARGIN = 20
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_H = 12
const LINE_HEIGHT = 6

// ─── Helpers ────────────────────────────────────────────────────────

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ]
}

function setColor(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setTextColor(r, g, b)
}

function setFillColor(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setFillColor(r, g, b)
}

function setDrawColor(doc: jsPDF, hex: string) {
  const [r, g, b] = hexToRgb(hex)
  doc.setDrawColor(r, g, b)
}

/** Check remaining space and add page + footer if needed. Returns current y. */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - MARGIN - FOOTER_H) {
    addFooter(doc)
    doc.addPage()
    return MARGIN
  }
  return y
}

function addFooter(doc: jsPDF) {
  setColor(doc, GRAY)
  doc.setFontSize(8)
  doc.text(
    'Generated by Gennoor Tech — gennoor.com',
    PAGE_W / 2,
    PAGE_H - 10,
    { align: 'center' },
  )
}

function drawSectionTitle(doc: jsPDF, y: number, title: string): number {
  y = ensureSpace(doc, y, 14)
  setFillColor(doc, BLUE)
  doc.rect(MARGIN, y, 3, 8, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  setColor(doc, DARK)
  doc.text(title, MARGIN + 6, y + 6)
  return y + 14
}

function drawWrappedText(
  doc: jsPDF,
  y: number,
  text: string,
  opts?: { fontSize?: number; color?: string; bold?: boolean; indent?: number },
): number {
  const fontSize = opts?.fontSize ?? 10
  const color = opts?.color ?? DARK
  const indent = opts?.indent ?? 0
  doc.setFont('helvetica', opts?.bold ? 'bold' : 'normal')
  doc.setFontSize(fontSize)
  setColor(doc, color)

  const maxW = CONTENT_W - indent
  const lines = doc.splitTextToSize(text, maxW)
  for (const line of lines) {
    y = ensureSpace(doc, y, LINE_HEIGHT + 1)
    doc.text(line, MARGIN + indent, y)
    y += LINE_HEIGHT
  }
  return y
}

function drawScoreBar(
  doc: jsPDF,
  y: number,
  label: string,
  score: number,
  insight?: string,
): number {
  y = ensureSpace(doc, y, 18)
  // Label
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  setColor(doc, DARK)
  doc.text(label, MARGIN, y)
  // Score number
  doc.text(`${score}/100`, MARGIN + CONTENT_W - 2, y, { align: 'right' })
  y += 4

  // Background bar
  const barW = CONTENT_W - 4
  const barH = 5
  setFillColor(doc, LIGHT_GRAY)
  doc.roundedRect(MARGIN, y, barW, barH, 2, 2, 'F')

  // Filled bar
  const filledW = (score / 100) * barW
  const barColor = score >= 70 ? ACCENT_GREEN : score >= 40 ? ACCENT_AMBER : '#ef4444'
  setFillColor(doc, barColor)
  if (filledW > 0) {
    doc.roundedRect(MARGIN, y, Math.max(filledW, 4), barH, 2, 2, 'F')
  }
  y += barH + 2

  // Insight
  if (insight) {
    y = drawWrappedText(doc, y, insight, { fontSize: 9, color: GRAY, indent: 2 })
  }
  y += 2
  return y
}

// ─── Header ─────────────────────────────────────────────────────────

function drawHeader(doc: jsPDF, userName: string, score: number): number {
  // Blue header band
  setFillColor(doc, BLUE)
  doc.rect(0, 0, PAGE_W, 52, 'F')

  // Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  setColor(doc, WHITE)
  doc.text('AI Readiness Report', MARGIN, 22)

  // Branding
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text('Gennoor Tech', MARGIN, 32)

  // User + date
  doc.setFontSize(9)
  const dateLine = `Prepared for ${userName} • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`
  doc.text(dateLine, MARGIN, 42)

  // Score circle (right side)
  const cx = PAGE_W - MARGIN - 18
  const cy = 26
  setFillColor(doc, WHITE)
  doc.circle(cx, cy, 16, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  setColor(doc, BLUE)
  doc.text(String(score), cx, cy + 2, { align: 'center' })
  doc.setFontSize(7)
  setColor(doc, GRAY)
  doc.text('/ 100', cx, cy + 9, { align: 'center' })

  return 60
}

// ═════════════════════════════════════════════════════════════════════
// Quick Scan PDF
// ═════════════════════════════════════════════════════════════════════

export function generateQuickScanPDF(
  report: any,
  userName: string,
  email: string,
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let y = drawHeader(doc, userName, report.score ?? 0)

  // ── Headline & Verdict ──
  y = drawWrappedText(doc, y, report.headline ?? '', {
    fontSize: 15,
    bold: true,
    color: DARK,
  })
  y += 2
  y = drawWrappedText(doc, y, report.verdict ?? '', {
    fontSize: 10,
    color: GRAY,
  })
  y += 6

  // ── Strengths ──
  y = drawSectionTitle(doc, y, 'Your Strengths')
  y = drawWrappedText(doc, y, report.strengthStatement ?? '')
  y += 6

  // ── Reality Check ──
  y = drawSectionTitle(doc, y, 'Reality Check')
  y = drawWrappedText(doc, y, report.realityCheck ?? '')
  y += 2
  if (report.timeWasted) {
    y = drawWrappedText(doc, y, `Time wasted on manual work: ${report.timeWasted}`, {
      fontSize: 10,
      bold: true,
      color: ACCENT_AMBER,
    })
  }
  y += 6

  // ── Pillars ──
  y = drawSectionTitle(doc, y, 'Readiness Pillars')
  if (Array.isArray(report.pillars)) {
    for (const p of report.pillars) {
      y = drawScoreBar(doc, y, p.name, p.score, p.insight)
    }
  }
  y += 4

  // ── Monday Before / After ──
  y = drawSectionTitle(doc, y, 'Your Monday — Before & After AI')
  const colW = (CONTENT_W - 6) / 2

  y = ensureSpace(doc, y, 10)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  setColor(doc, '#ef4444')
  doc.text('Before', MARGIN, y)
  setColor(doc, ACCENT_GREEN)
  doc.text('After', MARGIN + colW + 6, y)
  y += 6

  const beforeItems: string[] = report.mondayBefore ?? []
  const afterItems: string[] = report.mondayAfter ?? []
  const maxItems = Math.max(beforeItems.length, afterItems.length)

  for (let i = 0; i < maxItems; i++) {
    y = ensureSpace(doc, y, LINE_HEIGHT + 2)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)

    if (beforeItems[i]) {
      setColor(doc, DARK)
      const bLines = doc.splitTextToSize(`• ${beforeItems[i]}`, colW - 2)
      for (const bl of bLines) {
        y = ensureSpace(doc, y, LINE_HEIGHT)
        doc.text(bl, MARGIN, y)
        y += LINE_HEIGHT - 1
      }
      // Reset y back for after column if needed
      if (afterItems[i]) {
        y -= (bLines.length) * (LINE_HEIGHT - 1)
      }
    }

    if (afterItems[i]) {
      setColor(doc, DARK)
      const aLines = doc.splitTextToSize(`• ${afterItems[i]}`, colW - 2)
      let tempY = y
      for (const al of aLines) {
        tempY = ensureSpace(doc, tempY, LINE_HEIGHT)
        doc.text(al, MARGIN + colW + 6, tempY)
        tempY += LINE_HEIGHT - 1
      }
      // Use the larger y
      if (beforeItems[i]) {
        const bLines = doc.splitTextToSize(`• ${beforeItems[i]}`, colW - 2)
        y += Math.max(bLines.length, aLines.length) * (LINE_HEIGHT - 1)
      } else {
        y = tempY
      }
    }
    y += 1
  }
  y += 4

  // ── Quick Win ──
  if (report.quickWin) {
    y = drawSectionTitle(doc, y, `Quick Win: ${report.quickWin.title ?? ''}`)
    if (report.quickWin.timeframe) {
      y = drawWrappedText(doc, y, `Timeframe: ${report.quickWin.timeframe}`, {
        fontSize: 9,
        color: BLUE,
        bold: true,
      })
    }
    y += 2
    const steps: string[] = report.quickWin.steps ?? []
    for (let i = 0; i < steps.length; i++) {
      y = drawWrappedText(doc, y, `${i + 1}. ${steps[i]}`, { indent: 4 })
    }
    if (report.quickWin.expectedResult) {
      y += 2
      y = drawWrappedText(doc, y, `Expected result: ${report.quickWin.expectedResult}`, {
        fontSize: 9,
        color: ACCENT_GREEN,
        bold: true,
      })
    }
    y += 6
  }

  // ── Industry Insight ──
  if (report.industryInsight) {
    y = drawSectionTitle(doc, y, 'Industry Insight')
    y = drawWrappedText(doc, y, report.industryInsight)
    y += 2
  }
  if (report.peerComparison) {
    y = drawWrappedText(doc, y, report.peerComparison, {
      fontSize: 9,
      color: GRAY,
      indent: 2,
    })
    y += 6
  }

  // ── 30-Day Plan ──
  if (Array.isArray(report.thirtyDayPlan) && report.thirtyDayPlan.length > 0) {
    y = drawSectionTitle(doc, y, '30-Day Action Plan')
    for (const item of report.thirtyDayPlan) {
      y = ensureSpace(doc, y, LINE_HEIGHT + 2)
      setFillColor(doc, LIGHT_GRAY)
      doc.roundedRect(MARGIN, y - 4, CONTENT_W, LINE_HEIGHT + 4, 2, 2, 'F')
      y = drawWrappedText(doc, y, `• ${item}`, { indent: 4 })
      y += 3
    }
    y += 4
  }

  // ── Contact / CTA ──
  y = ensureSpace(doc, y, 30)
  setFillColor(doc, LIGHT_GRAY)
  doc.roundedRect(MARGIN, y, CONTENT_W, 24, 3, 3, 'F')
  y += 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  setColor(doc, DARK)
  doc.text('Ready to accelerate your AI journey?', PAGE_W / 2, y, { align: 'center' })
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  setColor(doc, BLUE)
  doc.text('Visit gennoor.com or email info@gennoor.com', PAGE_W / 2, y, { align: 'center' })

  addFooter(doc)
  return doc
}

// ═════════════════════════════════════════════════════════════════════
// Deep Dive PDF
// ═════════════════════════════════════════════════════════════════════

export function generateDeepDivePDF(
  report: any,
  userName: string,
  email: string,
): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let y = drawHeader(doc, userName, report.score ?? 0)

  // Headline
  y = drawWrappedText(doc, y, report.headline ?? '', {
    fontSize: 15,
    bold: true,
    color: DARK,
  })
  y += 6

  const slides: any[] = report.slides ?? []

  for (const slide of slides) {
    // Section heading from slide title
    y = drawSectionTitle(doc, y, slide.title ?? '')

    // Narration
    if (slide.narration) {
      y = drawWrappedText(doc, y, slide.narration, { fontSize: 9, color: GRAY })
      y += 4
    }

    const content = slide.content
    const type: string = slide.type ?? ''

    switch (type) {
      case 'score': {
        if (content && typeof content.score === 'number') {
          y = ensureSpace(doc, y, 20)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(28)
          setColor(doc, BLUE)
          doc.text(`${content.score}/100`, PAGE_W / 2, y + 10, { align: 'center' })
          y += 20
          if (content.verdict) {
            y = drawWrappedText(doc, y, content.verdict, { fontSize: 10, color: DARK })
          }
        }
        break
      }

      case 'strength': {
        if (typeof content === 'string') {
          y = drawWrappedText(doc, y, content)
        } else if (content?.statement) {
          y = drawWrappedText(doc, y, content.statement)
        }
        if (content?.highlights && Array.isArray(content.highlights)) {
          for (const h of content.highlights) {
            y = drawWrappedText(doc, y, `• ${h}`, { indent: 4 })
          }
        }
        break
      }

      case 'reality': {
        if (typeof content === 'string') {
          y = drawWrappedText(doc, y, content)
        } else if (content?.realityCheck) {
          y = drawWrappedText(doc, y, content.realityCheck)
          if (content.timeWasted) {
            y += 2
            y = drawWrappedText(doc, y, `Time wasted: ${content.timeWasted}`, {
              bold: true,
              color: ACCENT_AMBER,
            })
          }
        }
        break
      }

      case 'pillars': {
        const pillars = Array.isArray(content) ? content : content?.pillars
        if (Array.isArray(pillars)) {
          for (const p of pillars) {
            y = drawScoreBar(doc, y, p.name, p.score, p.insight)
          }
        }
        break
      }

      case 'monday': {
        if (content) {
          const before: string[] = content.before ?? content.mondayBefore ?? []
          const after: string[] = content.after ?? content.mondayAfter ?? []
          const colW2 = (CONTENT_W - 6) / 2

          y = ensureSpace(doc, y, 10)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(10)
          setColor(doc, '#ef4444')
          doc.text('Before', MARGIN, y)
          setColor(doc, ACCENT_GREEN)
          doc.text('After', MARGIN + colW2 + 6, y)
          y += 6

          const maxLen = Math.max(before.length, after.length)
          for (let i = 0; i < maxLen; i++) {
            y = ensureSpace(doc, y, LINE_HEIGHT + 2)
            doc.setFont('helvetica', 'normal')
            doc.setFontSize(9)
            setColor(doc, DARK)
            if (before[i]) {
              const bLines = doc.splitTextToSize(`• ${before[i]}`, colW2 - 2)
              let by = y
              for (const bl of bLines) {
                doc.text(bl, MARGIN, by)
                by += LINE_HEIGHT - 1
              }
            }
            if (after[i]) {
              const aLines = doc.splitTextToSize(`• ${after[i]}`, colW2 - 2)
              let ay = y
              for (const al of aLines) {
                doc.text(al, MARGIN + colW2 + 6, ay)
                ay += LINE_HEIGHT - 1
              }
            }
            // Advance y by max lines of either column
            const bCount = before[i] ? doc.splitTextToSize(`• ${before[i]}`, colW2 - 2).length : 0
            const aCount = after[i] ? doc.splitTextToSize(`• ${after[i]}`, colW2 - 2).length : 0
            y += Math.max(bCount, aCount) * (LINE_HEIGHT - 1) + 1
          }
        }
        break
      }

      case 'quickwin': {
        if (content) {
          if (content.title) {
            y = drawWrappedText(doc, y, content.title, { bold: true })
            y += 2
          }
          if (content.timeframe) {
            y = drawWrappedText(doc, y, `Timeframe: ${content.timeframe}`, {
              fontSize: 9,
              color: BLUE,
              bold: true,
            })
          }
          const steps: string[] = content.steps ?? []
          for (let i = 0; i < steps.length; i++) {
            y = drawWrappedText(doc, y, `${i + 1}. ${steps[i]}`, { indent: 4 })
          }
          if (content.expectedResult) {
            y += 2
            y = drawWrappedText(doc, y, `Expected result: ${content.expectedResult}`, {
              fontSize: 9,
              color: ACCENT_GREEN,
              bold: true,
            })
          }
        }
        break
      }

      case 'plan': {
        const planItems: string[] = Array.isArray(content) ? content : content?.steps ?? content?.plan ?? []
        for (const item of planItems) {
          y = ensureSpace(doc, y, LINE_HEIGHT + 4)
          setFillColor(doc, LIGHT_GRAY)
          doc.roundedRect(MARGIN, y - 4, CONTENT_W, LINE_HEIGHT + 4, 2, 2, 'F')
          y = drawWrappedText(doc, y, `• ${item}`, { indent: 4 })
          y += 3
        }
        break
      }

      case 'cta': {
        y = ensureSpace(doc, y, 30)
        setFillColor(doc, LIGHT_GRAY)
        doc.roundedRect(MARGIN, y, CONTENT_W, 24, 3, 3, 'F')
        y += 8
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(11)
        setColor(doc, DARK)
        const ctaText = typeof content === 'string' ? content : 'Ready to accelerate your AI journey?'
        doc.text(ctaText, PAGE_W / 2, y, { align: 'center' })
        y += 7
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        setColor(doc, BLUE)
        doc.text('Visit gennoor.com or email info@gennoor.com', PAGE_W / 2, y, { align: 'center' })
        y += 14
        break
      }

      default: {
        // Generic: render content as text if it's a string, or stringify
        if (content) {
          const text = typeof content === 'string' ? content : JSON.stringify(content, null, 2)
          y = drawWrappedText(doc, y, text, { fontSize: 9 })
        }
        break
      }
    }

    y += 6
  }

  // Final CTA if no CTA slide
  if (!slides.some((s) => s.type === 'cta')) {
    y = ensureSpace(doc, y, 30)
    setFillColor(doc, LIGHT_GRAY)
    doc.roundedRect(MARGIN, y, CONTENT_W, 24, 3, 3, 'F')
    y += 8
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    setColor(doc, DARK)
    doc.text('Ready to accelerate your AI journey?', PAGE_W / 2, y, { align: 'center' })
    y += 7
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    setColor(doc, BLUE)
    doc.text('Visit gennoor.com or email info@gennoor.com', PAGE_W / 2, y, { align: 'center' })
  }

  addFooter(doc)
  return doc
}

// ═════════════════════════════════════════════════════════════════════
// Utilities
// ═════════════════════════════════════════════════════════════════════

/** Trigger a browser download of the PDF */
export function downloadPDF(doc: jsPDF, fileName: string): void {
  doc.save(fileName)
}

/** Convert the PDF to a base64 string (for sending via API) */
export function pdfToBase64(doc: jsPDF): string {
  return doc.output('datauristring').split(',')[1]
}
