import type { Chapter } from '../_types.ts'
import { stepCard, calloutBlock } from '../_types.ts'

export const aiHealthcareChapter02: Chapter = {
  courseId: 'ai-in-healthcare',
  chapterId: 'chapter-02',
  chapterNumber: 2,
  chapterSlug: 'chapter-02-clinical-documentation',
  title: 'Clinical documentation AI',
  subtitle: 'The play that gives clinicians their evenings back — and the discipline that protects the chart.',
  slides: [
    // SLIDE 1
    {
      title: 'Clinical documentation AI',
      iconKey: 'bookOpen',
      eyebrow: 'Chapter 2 · Opening',
      bodyHtml: `<p class="lead">Physicians spend roughly two hours a day on EHR documentation. Clinical documentation AI cuts that meaningfully — and is among the most mature healthcare AI plays in production today. In the next few minutes, what to build, the disciplines that protect the chart, and the metrics that hold across years.</p>`,
      narrationLead:
        "Welcome to chapter two. Clinical documentation AI. Physicians spend roughly two hours a day on EHR documentation. That's two hours not spent with patients, not spent on continuing education, not spent at home with their families. Clinical documentation AI cuts that meaningfully — and is among the most mature healthcare AI plays in production today. In the next few minutes, what to build, the disciplines that protect the integrity of the chart, and the metrics that hold across years.",
    },
    // SLIDE 2
    {
      title: 'The three components of clinical documentation AI',
      iconKey: 'cog',
      eyebrow: 'Lesson 1 · The components',
      bodyHtml: `<p>Three components. Each one matters. Skipping any one weakens the chart and the deployment.</p>`,
      narrationLead:
        "Three components in clinical documentation AI done well. Each one matters. Skipping any one weakens the integrity of the chart and the credibility of the deployment.",
      steps: [
        {
          html: stepCard('cog', 'green', 'Component 1 — Ambient voice capture with consent',
            "Microphone in the consultation room captures the encounter. Patient consent obtained — explicitly, at first visit, refreshed annually. No covert recording. Ever. Consent is the first discipline."),
          narration:
            "Component one. Ambient voice capture with explicit patient consent. A microphone in the consultation room — sometimes the physician's mobile device, sometimes a dedicated unit — captures the encounter. Patient consent is obtained explicitly. Not buried in the general consent forms. Specifically. At the first visit. Refreshed annually. No covert recording, ever. Consent is the first discipline. Patients who opt out get the standard documentation workflow. Patients who consent get the AI assistance. The choice is theirs.",
        },
        {
          html: stepCard('cog', 'blue', 'Component 2 — Structured note generation',
            "From the captured encounter, the AI generates a structured note — SOAP format, problem-oriented note, or whatever your hospital's standard is. The note follows your template, your terminology, your local conventions. Not a generic note."),
          narration:
            "Component two. Structured note generation. From the captured encounter, the AI generates a structured clinical note. In your hospital's standard format — SOAP, problem-oriented, your local convention. The note follows your template, your terminology, your specialty's conventions. Not a generic note that the AI vendor designed for the average customer. Customisation to your hospital is what makes the note clinically usable. Generic notes get rewritten by physicians anyway, which defeats the purpose.",
        },
        {
          html: stepCard('cog', 'amber', 'Component 3 — Physician review and sign — always',
            "The note is a draft until the physician reviews and signs. The physician can edit, append, delete. The signature is what makes it the medical record. The AI is a typist, not an author. The signature is the line."),
          narration:
            "Component three. Physician review and signature — always. The note generated by the AI is a draft until the physician reviews and signs it. The physician can edit. Append. Delete. Reorganise. The signature is what makes it part of the medical record. The AI is a typist — a very capable typist — not an author. The physician's signature is the line that connects the documentation to the accountable clinician. Don't let any workflow shortcut compromise that signature step. Even if it adds thirty seconds.",
        },
      ],
      calloutHtml: calloutBlock('lightbulb', 'tip', 'The fourth, often-omitted discipline',
        "<strong>Selective ambient capture</strong>. The physician explicitly starts and stops the recording for each segment of the encounter. Sensitive parts — psychiatric history, sexual health, social context — can be excluded from capture entirely. The discipline reduces both privacy risk and physician hesitation."),
      calloutNarration:
        "A fourth discipline often omitted by vendors — selective ambient capture. The physician explicitly starts and stops the recording for each segment of the encounter. They can pause for a sensitive disclosure — psychiatric history, sexual health, social context — and document that part by hand or in a different style. The discipline reduces both privacy risk for the patient and hesitation on the part of the physician. Many physicians won't use ambient documentation if it's all-or-nothing. With selective capture, adoption goes up substantially. Build the selective control into the deployment. Vendors who can't accommodate it are the ones to question.",
    },
    // SLIDE 3
    {
      title: 'The integrity disciplines — what protects the chart',
      iconKey: 'shield',
      eyebrow: 'Lesson 2 · Chart integrity',
      bodyHtml: `<p>Three disciplines that protect the integrity of the medical record. None optional. Each one is what makes the deployment defensible in a future audit or legal review.</p>`,
      narrationLead:
        "Three disciplines that protect the integrity of the medical record. None of them is optional. Each one is what makes the deployment defensible in a future audit, an internal review, or a legal proceeding. Build all three from the start.",
      steps: [
        {
          html: stepCard('shield', 'blue', 'Discipline 1 — Full audit trail',
            "Every action logged. What the AI captured. What it transcribed. What it generated. What the physician edited. What the physician signed. Timestamped. Immutable. Retained per your retention policy."),
          narration:
            "Discipline one. Full audit trail. Every action in the documentation workflow is logged. What the microphone captured — the raw audio. What the AI transcribed — the text. What the AI generated — the structured note draft. What the physician edited — the diffs. What the physician signed — the final note. Each action timestamped. The log is immutable — meaning entries can be added but never quietly modified. Retained per your hospital's retention policy. The audit trail is what allows you to reconstruct any encounter at any future point. It is non-negotiable.",
        },
        {
          html: stepCard('shield', 'amber', 'Discipline 2 — Hallucination guardrails',
            "Generative AI can invent details. The system must constrain itself to facts present in the audio. Names, dosages, dates, lab values — these are never hallucinated. Either present in the transcript or flagged for the physician to add manually."),
          narration:
            "Discipline two. Hallucination guardrails. Generative AI can invent plausible-sounding details. In a clinical context, invented details are a patient-safety risk. The system must constrain itself to facts present in the audio transcript. Names. Dosages. Dates. Lab values. Vital signs. These are never hallucinated by the system. They are either present in the transcript — verbatim — or flagged for the physician to add manually after the conversation. Any vendor that can't articulate how their system prevents hallucination of clinical facts isn't ready for production deployment. Ask the question explicitly during evaluation.",
        },
        {
          html: stepCard('shield', 'green', 'Discipline 3 — Discrepancy surfacing',
            "When the AI's note differs from a fact in the EHR — say, a different medication name — the system surfaces the discrepancy to the physician. It doesn't silently override either. The clinician resolves. Sometimes the EHR is wrong; sometimes the conversation was. The discipline catches both."),
          narration:
            "Discipline three. Discrepancy surfacing. When the AI's generated note differs from a fact already in the EHR — for example, the AI heard a different medication name in the conversation than what's in the patient's medication list — the system surfaces the discrepancy to the physician. It doesn't silently override either source. The clinician resolves the discrepancy in the moment. Sometimes the EHR is wrong — the medication was changed and not updated. Sometimes the conversation was — the patient misremembered. Sometimes the AI mis-transcribed. The discipline catches all three. It also turns the AI into a useful safety check, not just a documentation accelerator. That dual value is what makes the deployment beloved by good clinicians.",
        },
      ],
    },
    // SLIDE 4
    {
      title: 'The metrics that hold across years',
      iconKey: 'target',
      eyebrow: 'Lesson 3 · Metrics',
      bodyHtml: `<p>Four metrics. Three operational. One clinical. The clinical one is the one most programmes forget — and the one that protects everyone in the long run.</p>`,
      narrationLead:
        "Four metrics for clinical documentation AI in steady state. Three operational — about workflow and adoption. One clinical — about chart integrity. The clinical one is the one most programmes forget. And it is the one that protects everyone in the long run. Track all four.",
      steps: [
        {
          html: stepCard('target', 'green', '1 · Documentation time per encounter (operational)',
            "Minutes spent documenting, measured against the pre-AI baseline. Realistic year-1 reduction — 40-60% for ambulatory care, 30-50% for inpatient. Track honestly; numbers above the band are usually self-report optimism."),
          narration:
            "Metric one. Documentation time per encounter. Operational. Minutes spent on documentation per encounter — measured against the pre-AI baseline. Realistic year-one reduction is forty to sixty percent for ambulatory care. Thirty to fifty percent for inpatient, where documentation is more complex. Track honestly. Numbers above those bands are usually self-report optimism. The honest number is what the CFO believes and what funds the next phase.",
        },
        {
          html: stepCard('target', 'blue', '2 · Physician satisfaction (operational, but human)',
            "Quarterly anonymous survey. Are you glad you have this. Would you recommend it to a colleague. Would you go back to manual documentation. The honest answers tell you whether the deployment is producing the experience you intended."),
          narration:
            "Metric two. Physician satisfaction. Operational, but the human side of operational. Quarterly anonymous survey. Are you glad you have access to this. Would you recommend it to a colleague at another hospital. Would you go back to manual documentation if given the choice. The honest answers tell you whether the deployment is producing the experience you intended. Not the experience the vendor's marketing claimed it would produce. The honest answers also surface issues early — before they become attrition, before they become formal complaints.",
        },
        {
          html: stepCard('target', 'amber', '3 · Adoption rate (operational)',
            "Percentage of eligible encounters where AI documentation was used. Target — 60%+ by month 6 for ambulatory, 40%+ for inpatient. Lower means the workflow isn't fitting; investigate before pushing."),
          narration:
            "Metric three. Adoption rate. The percentage of eligible patient encounters where AI documentation was actually used. Target by month six — sixty percent or higher in ambulatory care. Forty percent or higher in inpatient care, where the workflows are more variable. Lower numbers mean the workflow isn't fitting the clinical reality. Investigate before pushing for higher adoption. Pushing the wrong workflow harder doesn't fix it; it just burns physician goodwill.",
        },
        {
          html: stepCard('target', 'red', '4 · Chart integrity audit (clinical)',
            "Quarterly, internal audit reviews a random sample of AI-assisted notes. They compare the audio, the AI draft, and the physician-signed note. Discrepancies are surfaced. Patterns inform training. This is the metric most programmes skip — and the one that protects the hospital."),
          narration:
            "Metric four. Chart integrity audit. Clinical. Quarterly, internal audit — or the medical records team — reviews a random sample of AI-assisted notes. Typically twenty to fifty notes per quarter. They compare the audio, the AI's generated draft, and the physician's signed note. Discrepancies are surfaced. Patterns inform training for clinicians and adjustments to the AI configuration. This is the metric most healthcare AI programmes skip — and the one that protects the hospital in any future audit, regulator examination, or legal proceeding. Don't skip it. The cost is a few hours per quarter. The protection is significant.",
        },
      ],
    },
    // SLIDE 5
    {
      title: 'Key takeaways',
      iconKey: 'check',
      eyebrow: 'Chapter 2 · Takeaways',
      bodyHtml: `<p>Three anchors before chapter 3 — the patient journey copilot.</p>`,
      narrationLead:
        "Three anchors before chapter three — patient journey copilots.",
      steps: [
        {
          html: stepCard('check', 'green', 'One — Three components + selective capture',
            "Ambient capture with consent · structured note generation · physician review and sign. Plus selective capture for sensitive content. The fourth discipline lifts adoption substantially."),
          narration:
            "One. Three components plus selective capture as a fourth discipline. Ambient capture with explicit consent. Structured note generation in your hospital's format. Physician review and signature always. Plus selective capture — the physician starting and stopping the recording for each segment. The fourth discipline lifts adoption substantially, particularly among physicians cautious about ambient recording.",
        },
        {
          html: stepCard('check', 'green', 'Two — Three integrity disciplines, non-negotiable',
            "Full audit trail · hallucination guardrails · discrepancy surfacing. The disciplines that protect the chart — and protect everyone using the system."),
          narration:
            "Two. Three integrity disciplines, all non-negotiable. Full audit trail of every action in the workflow. Hallucination guardrails preventing the AI from inventing clinical facts. Discrepancy surfacing when the AI's draft differs from the EHR. The disciplines that protect the chart — and protect everyone using the system, including the hospital itself.",
        },
        {
          html: stepCard('check', 'green', 'Three — Four metrics, including chart integrity audit',
            "Documentation time · physician satisfaction · adoption rate · chart integrity audit. The fourth is the most forgotten. Track all four."),
          narration:
            "Three. Four metrics. Documentation time per encounter. Physician satisfaction. Adoption rate. And the chart integrity audit — the most forgotten metric. Track all four. The chart integrity audit is the metric that protects the hospital in any future review. Don't skip it because it's quarterly work. The cost is small. The protection is large.",
        },
      ],
      narrationTrail:
        "Chapter three — patient journey copilots. Where AI helps without touching the clinical decision. See you there.",
    },
  ],
}
